name: Copilot Usage Metrics Export
on:
  workflow_dispatch:

jobs:
  run:
    name: Copilot Usage Metrics Export Action
    runs-on: ubuntu-latest
    steps:
      - uses: bthomas2622/copilot-metrics-export-action@v1.1
        with:
          access-token: ${{ secrets.authorized_pat}}
          org-summary: true
          org-name: felipementel-org
          # enterprise-summary: true
          # enterprise-name: myenterpriseo
          # team-summary: true
          # team-name: engineering
