name: Modelo com echo

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:

env:
  imageName: xxx.api
  dotnetVersion: 8.x
  csprojFolder: ./src/DEPLOY.xxx.Api/DEPLOY.xxx.Api.csproj

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Executando do modelo
        run: |
          echo felipe
