name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:

env:
  imageName: cachorro.api
  dotnetVersion: 7.x
  csprojFolder: ./src/DEPLOY.Cachorro.Api/DEPLOY.Cachorro.Api.csproj

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        run: |
          echo felipe
